#! perl

# This extesion allows you to configure shortcuts to copy to and
# paste from the clipboard.
#
# Setup:
# - Add this file to the directory ~/.urxvt/ext/ .
# - Add the following lines to your ~/.Xresources or ~/.Xdefaults:
#
#     URxvt*keysym.Control-Shift-C: clipboard-shortcuts:copy
#     URxvt*keysym.Control-Shift-V: clipboard-shortcuts:paste

sub on_action {
    my ($self, $action) = @_;

    if($action eq "copy") {
        $self->selection($self->selection(), 1);
        $self->selection_grab(urxvt::CurrentTime, 1);
    }
    elsif($action eq "paste") {
        $self->selection_request(urxvt::CurrentTime, 3);
    }
    ()
}
